mod simple_text_output;
mod simple_text_input;
pub use simple_text_output::{SimpleTextOutputProtocol,SimpleTextOutputProtocolWrapper,SimpleTextOutputMode};
pub use simple_text_input::{SimpleTextInputProtocol,SimpleTextInputProtocolWrapper,KeyState,KeyData,KeyNotifyFunction,KeyToggleState,KeyShiftState};
